language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements-test.txt
script: py.test

jobs:
  include:
    - stage: pypi deploy
      deploy:
        provider: pypi
        user: rolze
        # TEST pypi server
        server: https://test.pypi.org/legacy/
        password:
          secure: duPi+RvmDJyiGHwzQjt9EVqJZUCleyPjc4pYn69dqmA0X4E09dEoqrKHDSJkxEa8KTlkigQk9yx0h7Da6CWXjZBjsdI4UGTGWAvGagn0BkzWjesCXW1dvANSDaokpU8iKxL0qz/Om4uy+GdK/A540uhGD7FMq/XpINSv6CHGYp3eBtY/C+XNlUgV6RXBL7HU6maIASjkZcmNfsYsZm2pAVZ28Sv+jzaBb3aajeZxL6TtaRbUs8YiK7DwL8h9lF8nqsg57D2o0dX2l637qjOKs/lZHsDGhNsTYCTUNnjpzXMl9TyjnYbt7lcWA2ddTMWeNxxn/+F8siuIuti4ibo3fZUouYQz5FO+Db6Wnh38sya2u8uEoe55gpJz/NPbJnq03TNKr/vYVHz8jA2ELChWG2451XQwr6ynbvMYf+mGUgwyC9uajWfIC29OoBeqctRHJ1vVLQ7D3hk4pmd/tAqANF4qCpq0N2BdPH02mwk1vuyxklkbSbohSukpguVdZXER+daAvdSUlOzi+0bWBS8s2mxGpvi66pfp5QWENpQkVMlsEZV52gxQWNa20rx8c49jJD9zdyNXXqHue1N2cEywFBCeIgwlRTHoE528B+7cjwG7Z3TIMSSlnkUqm89WIcVFhJhZX9BIs+q1KerME0Qxb555vrCe1dY0xdQwYWacpLQ=
        on:
          # tags: true
          distributions: "sdist bdist_wheel"
          repo: ifxit/nidhogg
