language: python
python:
- '2.7'
- '3.4'
- '3.5'
install: pip install -r nidhogg/requirements-test.txt
script: py.test
before_deploy: cd nidhogg
deploy:
  provider: pypi
  user: rolze
  password:
    secure: CEOUrtM4ng/FspQuFrgjdL+rQ1uqqeJMX23ShA4yCX/f5b37oF7llSWJOMVEsh4KFV4mv1UUFEVUaRxF8YGiNlgzPnedeiorLE6wBCMg3/8vnESgR45bAbjPnfaBvAkpSfwcoVMsuGCT7vKU9Mlb4D0MNXBLEMIA/l4f5tKjaJiBFk4Xdt1chNKxjyJZyi/fcjjLC5qjT0pPKWmUoUksAmWCPqmbpFPr5eZa02VRigwauVnAySAdBNyl2P/Y2+g5G7etpi5F7UqM1x0L+tLQkw6mvTaKxnmDanGUa9CfmUfRp35UPO+yFSSp2Qf5+xVb6KxdV4ya8CbQUzhXGV8MGVNv1BU93GDoMpL9OavrnUUpuZJACrWZGtWfLyJ5Fg7qpNgyzljfbSbWlXBZAZXjHBpVMeZwnWGs8CQ5jto3bLIRFBEcIH61R7jQHEXQgHjg2S0YG4FBTrNT9IzXIq07el2rPR3iaMqTUibsHtIvuCZWmKISw2XWDr9W2jmol9o70lClb/jaAPZKPVe4abWFc4NcekrTGmXi8kskW+UTALp/Lt8CNYMSX/Xdw4/rO1UBxYoxtAvECVjkHr67qInYN4xj9qPuV8sQbyUAe5Bb0eEX6kolOd5/eE3pJv0oyncEwRl1ixD1meRgwdikzzDWwTPL4tNxdzCVGRNIp9fdCRU=
  on:
    tags: true
    distributions: sdist
    repo: ifxit/nidhogg
